# overall--------------------------------------------------------------  
# (C)Copyright 2001,2006,                                         
# International Business Machines Corporation,                    
# Sony Computer Entertainment, Incorporated,                      
# Toshiba Corporation,                                            
#                                                                 
# All Rights Reserved.                                            
# --------------------------------------------------------------  
# PROLOG END TAG zYx                                              

########################################################################
#			Subdirectories
########################################################################

DIRS		:= 	spu ppu


########################################################################
#                       Target
########################################################################

#PROGRAM_ppu	:= 	st_online_ppu

########################################################################
#                       Local Defines
########################################################################

#IMPORTS         := spu/lib_st_online_spu.a -lspe

#INSTALL_DIR	= $(SDKBIN)/suffixtree
#INSTALL_FILES	= $(PROGRAM_ppu)

########################################################################
#			make.footer
########################################################################

ifdef CELL_TOP
	include $(CELL_TOP)/make.footer
else
	include ../../../make.footer
endif
