# ppu--------------------------------------------------------------  
# (C)Copyright 2001,2006,                                         
# International Business Machines Corporation,                    
# Sony Computer Entertainment, Incorporated,                      
# Toshiba Corporation,                                            
#                                                                 
# All Rights Reserved.                                            
# --------------------------------------------------------------  
# PROLOG END TAG zYx                                              

########################################################################
#			Target
########################################################################

PROGRAM_ppu	= $(SDKBIN)/samples/suffixtree


########################################################################
#			Local Defines
########################################################################

IMPORTS 	= ../spu/st_online_spu.a -lspe


########################################################################
#			make.footer
########################################################################

ifdef CELL_TOP
	include $(CELL_TOP)/make.footer
else
	include ../../../../make.footer
endif
